-- MySQL Script generated by MySQL Workbench
-- 03/06/18 17:48:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fet16016703
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `twitterAPI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitterAPI` (
  `tweetID` INT NOT NULL AUTO_INCREMENT,
  `tweetAuthor` VARCHAR(45) NULL,
  `tweetText` VARCHAR(150) NULL,
  `tweetAuthorPic` VARCHAR(200) NULL,
  `tweetAdditionDate` DATETIME NULL,
  PRIMARY KEY (`tweetID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
