-- MySQL Script generated by MySQL Workbench
-- 03/04/18 16:13:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fet15021296
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  `population` INT NOT NULL,
  `national_language` VARCHAR(20) NOT NULL,
  `gdp` INT NOT NULL,
  `wiki_link` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `city` ;

CREATE TABLE IF NOT EXISTS `city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(120) NOT NULL,
  `geocode_latitude` DECIMAL(9,6) NOT NULL,
  `geocode_longitude` DECIMAL(9,6) NOT NULL,
  `country` INT NOT NULL,
  `woeid` INT NOT NULL,
  `county_state` VARCHAR(20) NOT NULL,
  `population` INT NOT NULL,
  `area` INT NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `primary_language` VARCHAR(15) NOT NULL,
  `wiki_link` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_City_Country_idx` (`country` ASC),
  CONSTRAINT `fk_City_Country`
    FOREIGN KEY (`country`)
    REFERENCES `country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather_codes` ;

CREATE TABLE IF NOT EXISTS `weather_codes` (
  `weather_code_id` INT NOT NULL,
  `description` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`weather_code_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather` ;

CREATE TABLE IF NOT EXISTS `weather` (
  `city_id` INT NOT NULL,
  `last_checked` DATETIME NOT NULL,
  `published_at` DATETIME NOT NULL,
  `current_temp` INT NOT NULL,
  `weather_code` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_Weather_City1_idx` (`city_id` ASC),
  INDEX `fk_Weather_weather_codes1_idx` (`weather_code` ASC),
  CONSTRAINT `fk_Weather_City1`
    FOREIGN KEY (`city_id`)
    REFERENCES `city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Weather_weather_codes1`
    FOREIGN KEY (`weather_code`)
    REFERENCES `weather_codes` (`weather_code_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `local_attractions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `local_attractions` ;

CREATE TABLE IF NOT EXISTS `local_attractions` (
  `local_attractions_id` INT NOT NULL AUTO_INCREMENT,
  `city` INT NOT NULL,
  `attraction_name` VARCHAR(45) NOT NULL,
  `geocode_latitude` DECIMAL(9,6) NOT NULL,
  `geocode_longitude` DECIMAL(9,6) NOT NULL,
  `website` VARCHAR(100) NOT NULL,
  `rating` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`local_attractions_id`),
  INDEX `fk_local_attractions_City1_idx` (`city` ASC),
  CONSTRAINT `fk_local_attractions_City1`
    FOREIGN KEY (`city`)
    REFERENCES `city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venue_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venue_category` ;

CREATE TABLE IF NOT EXISTS `venue_category` (
  `venue_category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`venue_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attraction_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attraction_categories` ;

CREATE TABLE IF NOT EXISTS `attraction_categories` (
  `venue_category` INT NOT NULL,
  `local_attraction` INT NOT NULL,
  INDEX `fk_attraction_categories_Venue_category1_idx` (`venue_category` ASC),
  INDEX `fk_attraction_categories_local_attractions1_idx` (`local_attraction` ASC),
  PRIMARY KEY (`venue_category`, `local_attraction`),
  CONSTRAINT `fk_attraction_categories_Venue_category1`
    FOREIGN KEY (`venue_category`)
    REFERENCES `venue_category` (`venue_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attraction_categories_local_attractions1`
    FOREIGN KEY (`local_attraction`)
    REFERENCES `local_attractions` (`local_attractions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forecast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forecast` ;

CREATE TABLE IF NOT EXISTS `forecast` (
  `date_offset` INT NOT NULL,
  `weather_code` INT NOT NULL,
  `temp_high` INT NOT NULL,
  `temp_low` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`date_offset`, `city_id`),
  INDEX `fk_forecast_weather_codes1_idx` (`weather_code` ASC),
  INDEX `fk_forecast_City1_idx` (`city_id` ASC),
  CONSTRAINT `fk_forecast_weather_codes1`
    FOREIGN KEY (`weather_code`)
    REFERENCES `weather_codes` (`weather_code_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forecast_City1`
    FOREIGN KEY (`city_id`)
    REFERENCES `city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `weather_codes`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (1, 'tropical storm');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (2, 'hurricane');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (3, 'severe thunderstorms');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (4, 'thunderstorms');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (5, 'mixed rain and snow');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (6, 'mixed rain and sleet');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (7, 'mixed snow and sleet');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (8, 'freezing drizzle');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (9, 'drizzle');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (10, 'freezing rain');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (11, 'showers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (12, 'showers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (13, 'snow flurries');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (14, 'light snow showers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (15, 'blowing snow');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (16, 'snow');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (17, 'hail');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (18, 'sleet');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (19, 'dust');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (20, 'foggy');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (21, 'haze');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (22, 'smoky');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (23, 'blustery');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (24, 'windy');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (25, 'cold');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (26, 'cloudy');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (27, 'mostly cloudy (night)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (28, 'mostly cloudy (day)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (29, 'partly cloudy (night)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (30, 'partly cloudy (day)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (31, 'clear (night)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (32, 'sunny');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (33, 'fair (night)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (34, 'fair (day)');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (35, 'mixed rain and hail');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (36, 'hot');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (37, 'isolated thunderstorms');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (38, 'scattered thunderstorms');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (39, 'scattered thunderstorms');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (40, 'scattered showers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (41, 'heavy snow');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (42, 'scattered snow showers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (43, 'heavy snow');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (44, 'partly cloudy');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (45, 'thundershowers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (46, 'snow showers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (47, 'isolated thundershowers');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (3200, 'not available');
INSERT INTO `weather_codes` (`weather_code_id`, `description`) VALUES (0, 'tornado');

COMMIT;

